# Generated by Django 4.2.1 on 2023-05-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customer_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='package',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
